### PR TITLE
update data structure lesson

### PR DESCRIPTION
**Pull request by raynamharris**
Okay, this is a large pull request, probably should have broken it up, but well, I didn't. Major changes include:

- translate the example cat dataset (as per #93 and #78)
- slimmed the discussion of vectors a lot!
- added a box explaining the `nrow` and `rbind` functions in Spanish

### CODE REVIEW

**Comment by raynamharris** [comment]
cc @rociotmartinez @rodriguezmDNA @flor14

**Comment by spereyra** [comment]
Great work @raynamharris! I agree.
I recently merged a PR with typos (#95 ) that prevents to merge this. Sorry! Should have waited till this was merged first...

**Comment by spereyra** [comment]
Merge conflict resolved. If you agree, then I am OK to merge this PR.

**Comment by raynamharris** [comment]
Excellent thanks @spereyra !

**Pull request merged**
